version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - backend

volumes:
  bundle:
  node_modules: